version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11  # or 3.9, depending on your app
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo Pre-build phase started...
      - echo Nothing to do here for now

  build:
    commands:
      - echo Build phase started...
      - python -m py_compile app.py  # Replace with your main file

  post_build:
    commands:
      - echo Build completed successfully.
      - echo Ready to deploy or run the app.

artifacts:
  files:
    - '**/*'
