version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt

  build:
    commands:
      - echo "Running app build tasks..."
      - python -m py_compile prediction/forecast/apps.py

  post_build:
    commands:
      - echo "Post-build: Copying files to EC2 and starting app..."
      - scp -i chennapragada.pem -o StrictHostKeyChecking=no -r * ec2-user@54.234.4.68:/home/ec2-user/
      - ssh -i chennapragada.pem -o StrictHostKeyChecking=no ec2-user@54.234.4.68 "cd /home/ec2-user/ && nohup python3 app.py > log.txt 2>&1 &"

artifacts:
  files:
    - '**/*'
